# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "kiz-app"
client_id = "5aedb02a0daec079797f1ba2ed6f0aa6"
application_url = "https://b049-118-71-165-20.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_customers"

[auth]
redirect_urls = [
  "https://b049-118-71-165-20.ngrok-free.app/auth/callback",
  "https://b049-118-71-165-20.ngrok-free.app/auth/shopify/callback",
  "https://b049-118-71-165-20.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-bc83118a.myshopify.com"
